services:
  mysql:
    container_name: mysql
    build:
      context: ./containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: miniintern
      MYSQL_USER: miniintern_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes:
      - miniintern_mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"

  migrator:
    container_name: migrator
    build:
      context: ./containers/migrator
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: miniintern
      DB_PORT: "3306"
      DB_USERNAME: miniintern_user
    command: >
      sh -c '
          bash /migrator/migrate.sh $$DB_HOST $$DB_PORT $$DB_NAME $$DB_USERNAME /run/secrets/mysql_user_password up
      '
    secrets:
      - mysql_user_password

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password

volumes:
  miniintern_mysql_data:
